Backport PARQUET-806: Parquet-tools silently suppresses error messages
The "error message" that used to be

org/apache/hadoop/conf/Configuration

now becomes:

NoClassDefFoundError: org/apache/hadoop/conf/Configuration

Author: Zoltan Ivanfi <zi@cloudera.com>

Closes #396 from zivanfi/PARQUET-806 and squashes the following commits:

b1fe699 [Zoltan Ivanfi] PARQUET-806: Parquet-tools silently suppresses error messages

(cherry picked from commit 3634821fa515365618209f0452443728e7290fca)

Change-Id: I46ade5f65b5be7f7eec96e8059446899080cebe0